### ISSUE TITLE
exception when trying to close sapui5 application with id / adding object "component" with duplicate id 

### ISSUE THREAD

**Issue by gregorwolf** [aydin-ozcan/generator-ui5-react-nest#3]
Hi @aydin-ozcan,

I've used the generator to create [ui5-react-nest-hello-world](https://github.com/gregorwolf/ui5-react-nest-hello-world). Unfortunately it seems that the lifecycle required to make the react app run correctly inside the launchpad isn't yet supported. 

Please try this steps to replicate the issue:

- start the example 
- access http://localhost:8080/launchpad.html?sap-language=en#helloworldui-display
- Start the developer tools
- now click on the SAP logo to navigate back to the startpage of the launchpad

In the console you will see this error:

```
2023-07-31 22:33:12.102699 exception when trying to close sapui5 application with id 'application-helloworldui-display'. This error must be fixed in order for FLP to operate properly.
 - TypeError: lr.unmountComponentAtNode is not a function
    at p.unloadApp (http://localhost:8080/ExtApp/react.js:40:57757)
    at p.destroy (http://localhost:8080/ExtApp/UI5Nest.js:48:12)
    at y.destroyAggregation (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:326:15902)
    at y.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:326:20064)
    at d.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:404:3433)
    at u.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap/ui/core/Control.js:6:4343)
    at y.destroyAggregation (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:326:15902)
    at y.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:326:20064)
    at d.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap-ui-core.js:404:3433)
    at u.destroy (https://sapui5.hana.ondemand.com/1.108.19/resources/sap/ui/core/Control.js:6:4343)
```

I think this is also the reason why the app can't be started a second time. When clicking on the tile I see this error in the console:

```
Log-dbg.js:452 2023-07-31 22:37:07.290300 adding object "component" with duplicate id 'application-helloworldui-display-component' -
```

CU
Gregor

**Comment by aydin-ozcan** [comment]
Hi @gregorwolf ,

Thank you for trying the generator . your interest and inputs are very valuable ,  it looks like react deprecated how we use to unload the react application.
https://react.dev/reference/react-dom/unmountComponentAtNode
I have change it to the new way. Now it works. I made a pr for the change at repo ui5-react-nest-hello-world.
I ll update generator also .
Thank you
